import type { Profile } from "./types.ts";

/** Hormonal, digestive, life-stage, performance and lifestyle profiles. */
export const PROFILES_B: Profile[] = [
  {
    key: "pcos-ir",
    label: "PCOS — Insulin Resistant",
    category: "Hormonal",
    conditions: ["PCOS / PCOD"],
    dietPreference: "Vegetarian",
    focus: "Insulin sensitivity first — carb quality, pairing and steady timing before any calorie restriction.",
    wakeup: ["Methre wala paani — 1 glass", "5 soaked almonds + 2 walnuts", "1 tsp soaked flaxseed"],
    breakfasts: [
      "2 moong dal cheela with curd — protein-led start",
      "Besan chilla with paneer stuffing — 2 pieces",
      "Vegetable oats with 1 tsp flaxseed and pumpkin seeds",
      "2 multigrain roti with paneer bhurji",
      "Sprouted moong salad with 1 multigrain toast",
    ],
    midMorning: ["Guava + 10 pumpkin seeds", "Apple + 5 almonds", "Buttermilk with jeera", "Roasted chana"],
    lunches: [
      "Salad first, then 2 jowar roti + dal + green sabzi + curd",
      "1 katori brown rice + rajma + large salad + curd",
      "2 multigrain roti + chana dal + methi sabzi",
      "Quinoa + mixed vegetables + paneer 60 gm",
    ],
    evenings: ["Roasted chana + green tea", "Sprouts chaat with lemon", "Buttermilk + pumpkin seeds", "Makhana roasted in 1 tsp ghee"],
    dinners: [
      "1-2 roti + paneer sabzi + salad — by 8:30 pm",
      "Moong dal khichdi with curd",
      "Vegetable soup + 1 roti with dal",
      "Tofu or paneer stir-fry with sautéed greens",
    ],
    bedtime: ["Warm turmeric milk", "Magnesium glycinate — as advised"],
    supplements: ["Omega 3 — 1 cap", "Vitamin D — as advised by your doctor"],
    practices: ["Strength training 3x/week — muscle improves insulin sensitivity", "Walk 30 min daily", "Sleep before 11 pm"],
    guidelines: [
      "Protein at every single meal. This is the change that shifts cravings most.",
      "Never eat a carbohydrate alone — always with protein, fat or fibre.",
      "No long gaps. The crash-and-crave cycle is what makes PCOS eating so hard to control.",
      "Sleep and stress affect the hormonal picture directly. They are part of the plan, not extras.",
      "Blanket gluten-free and dairy-free are not needed for most people with PCOS.",
      "Track energy, cravings, sleep and cycle — these often improve before the scale does.",
    ],
    notes: ["Weight moves more slowly with PCOS. That is physiology, not failure."],
  },
  {
    key: "pcos-lean",
    label: "PCOS — Lean",
    category: "Hormonal",
    conditions: ["PCOS / PCOD"],
    dietPreference: "Vegetarian",
    focus: "Symptom and cycle support without weight loss — nutrient adequacy and stable blood sugar.",
    wakeup: ["Warm water with lemon", "5 soaked almonds + 2 walnuts", "1 tsp soaked flaxseed"],
    breakfasts: [
      "2 moong dal cheela with curd and chutney",
      "Vegetable oats with milk, seeds and nuts",
      "Paneer paratha with curd — 1 piece, 1 tsp ghee",
      "Besan chilla with vegetables and curd",
    ],
    midMorning: ["Banana with peanut butter", "Guava + pumpkin seeds", "Dates with almonds", "Buttermilk"],
    lunches: [
      "2 roti + dal + paneer sabzi + curd + salad",
      "1 katori rice + rajma + curd + salad + 1 tsp ghee",
      "2 jowar roti + chana + sautéed greens + curd",
      "Quinoa pulao with paneer and raita",
    ],
    evenings: ["Sprouts chaat", "Roasted chana + green tea", "Dry fruit and seed mix", "Lassi"],
    dinners: [
      "2 roti + paneer sabzi + salad",
      "Vegetable khichdi with ghee and curd",
      "Dal + sautéed greens + 1 roti",
      "Tofu stir-fry with 1 roti",
    ],
    bedtime: ["Warm turmeric milk with 2 soaked dates"],
    supplements: ["Omega 3 — 1 cap", "Vitamin D and B12 — as advised"],
    practices: ["Yoga and strength work, not excessive cardio", "Sleep before 11 pm", "Bhramari — 5 rounds at night"],
    guidelines: [
      "This plan is not for weight loss. Do not cut calories.",
      "Excess cardio can worsen lean PCOS. Prioritise strength and yoga.",
      "Eat every 3 hours to keep blood sugar steady.",
      "Track cycle regularity, energy, skin and hair alongside any weight change.",
    ],
  },
  {
    key: "hypothyroid",
    label: "Hypothyroidism",
    category: "Hormonal",
    conditions: ["Thyroid"],
    dietPreference: "Vegetarian",
    focus: "Medication timing, nutrient adequacy and realistic expectations about the rate of change.",
    wakeup: [
      "Thyroid medication on an empty stomach — water only",
      "Wait at least 45-60 minutes before anything else",
      "Then: 5 soaked almonds + 2 brazil nuts",
    ],
    breakfasts: [
      "Vegetable oats with pumpkin seeds — 1 katori",
      "2 besan chilla with curd",
      "Moong dal cheela with chutney",
      "2 multigrain roti with paneer bhurji",
    ],
    midMorning: ["Guava or apple", "Buttermilk", "Roasted chana", "Handful of pumpkin seeds"],
    lunches: [
      "Salad + 2 roti + dal + green sabzi + curd",
      "1 katori rice + rajma + salad + curd",
      "2 jowar roti + chana dal + palak sabzi",
      "Vegetable khichdi with curd",
    ],
    evenings: ["Green tea + roasted chana", "Sprouts chaat", "Buttermilk", "Makhana"],
    dinners: [
      "1-2 roti + paneer sabzi + salad",
      "Moong dal khichdi with curd",
      "Vegetable soup + 1 roti with dal",
      "Dal + sautéed greens + 1 roti",
    ],
    bedtime: ["Warm milk — keep 4 hours away from any iron or calcium supplement"],
    supplements: ["Selenium via 2 brazil nuts daily", "Vitamin D and B12 — as advised"],
    guidelines: [
      "Take thyroid medication on an empty stomach and wait 45-60 minutes before food, tea or coffee.",
      "Keep calcium and iron supplements at least 4 hours away from thyroid medication.",
      "Cooked cruciferous vegetables in normal amounts are fine. The blanket ban is overstated.",
      "Use iodised salt in normal cooking. Do not supplement iodine without your doctor's advice.",
      "Weight change is slower with a thyroid condition. Slower is not never.",
      "Constipation is common here — fibre, fluid and daily walking address it.",
    ],
    notes: ["No food treats a thyroid condition. Your medication does that. This plan supports how you feel."],
  },
  {
    key: "menopause",
    label: "Menopause & Perimenopause",
    category: "Hormonal",
    conditions: ["Menopause"],
    dietPreference: "Vegetarian",
    focus: "Bone density, muscle retention and sleep — the three things that quietly decline in this phase.",
    wakeup: ["Warm water with lemon", "5 soaked almonds + 2 walnuts", "1 tsp soaked flaxseed — phytoestrogens"],
    breakfasts: [
      "Ragi porridge with milk and nuts",
      "2 besan chilla with curd",
      "Vegetable oats with flaxseed and pumpkin seeds",
      "Paneer stuffed roti with curd",
    ],
    midMorning: ["Sesame ladoo — 1 small", "Curd with fruit", "Handful of almonds", "Buttermilk"],
    lunches: [
      "Salad + 2 ragi or jowar roti + dal + green sabzi + curd",
      "Brown rice + rajma + salad + curd",
      "2 roti + paneer sabzi + palak + curd",
      "Quinoa with vegetables and paneer",
    ],
    evenings: ["Green tea + roasted chana", "Sesame and jaggery — 1 small piece", "Buttermilk", "Handful of walnuts"],
    dinners: [
      "1-2 roti + dal + sautéed greens",
      "Vegetable khichdi with curd",
      "Paneer sabzi with 1 roti and salad",
      "Vegetable soup + 1 roti",
    ],
    bedtime: ["Warm turmeric milk", "Magnesium glycinate — as advised, supports sleep"],
    supplements: ["Vitamin D and calcium — as advised by your doctor", "Omega 3 — 1 cap"],
    practices: ["Strength training 3x/week — the single best intervention for bone and muscle", "Walk 30-40 min daily", "Bhramari before bed"],
    guidelines: [
      "Calcium and vitamin D adequacy matters more now than at any earlier stage.",
      "Protein at every meal — muscle loss accelerates through this phase.",
      "Sesame, flaxseed and soya in normal amounts provide phytoestrogens.",
      "Limit caffeine after 4 pm and alcohol entirely if hot flushes or sleep are disturbed.",
      "Weight-bearing exercise is not optional here.",
    ],
  },
  {
    key: "period-support",
    label: "Period & Cycle Support",
    category: "Hormonal",
    conditions: ["Menstrual health"],
    dietPreference: "Vegetarian",
    focus: "Iron, magnesium and anti-inflammatory support through the menstrual phase.",
    wakeup: ["Warm water with lemon and chia", "5-6 soaked almonds + 2 walnuts", "1 tsp flaxseed or soaked sabja"],
    breakfasts: [
      "Beetroot, carrot and amla juice + besan chilla",
      "Moong dal dosa with coconut chutney",
      "Ragi porridge with dates and nuts",
      "Vegetable poha with peanuts",
    ],
    midMorning: ["1 cube dark chocolate + handful of makhana", "Coconut water", "Dates with almonds", "Papaya"],
    lunches: [
      "Quinoa + beetroot + dal + mixed vegetables + curd",
      "2 roti + palak dal + salad + curd",
      "Rice + rajma + sautéed greens + curd",
      "Khichdi with ghee, curd and beetroot salad",
    ],
    evenings: ["Herbal tea (ginger, tulsi, cinnamon) + 10 pumpkin seeds", "Sesame ladoo", "Buttermilk", "Dark chocolate + nuts"],
    dinners: [
      "Dal soup or vegetable jowar khichdi",
      "Stir-fried leafy greens with 1 roti",
      "Moong dal khichdi with ghee",
      "Vegetable soup + 1 roti",
    ],
    bedtime: ["Warm turmeric milk", "Triphala — 2 cap, if constipated"],
    practices: ["Light yoga or walking — circulation and cramp relief", "Pawanmuktasana and gentle stretching"],
    guidelines: [
      "Hydrate hard: 2.5 to 3 litres including coconut water, to reduce bloating.",
      "Limit caffeine and salt through the week to prevent water retention.",
      "Increase fibre — constipation is common in this phase.",
      "Iron-rich foods with vitamin C: palak with lemon, beetroot with amla.",
      "Gentle movement, not intense training, during the heaviest days.",
    ],
  },
  {
    key: "bloating-acidity",
    label: "Bloating & Acidity",
    category: "Digestive",
    conditions: ["Digestive issues"],
    dietPreference: "Vegetarian",
    focus: "Fix the pattern first — timing, portion, eating speed and fibre type — before removing any food.",
    wakeup: ["Warm water with 1 tsp soaked saunf", "Chew ½ inch raw ginger", "5 soaked and peeled almonds"],
    breakfasts: [
      "Vegetable dalia — well cooked, 1 katori",
      "Moong dal cheela — light, with pudhina chutney",
      "Poha with vegetables, low oil",
      "Oats cooked soft with milk",
    ],
    midMorning: ["Papaya — 1 katori", "Banana", "Buttermilk with jeera and dry ginger", "Coconut water"],
    lunches: [
      "2 roti + moong dal + well-cooked lauki sabzi + curd",
      "Soft khichdi with 1 tsp ghee and curd",
      "1 katori rice + dal + steamed vegetables",
      "2 roti + tinda or ghiya sabzi + curd",
    ],
    evenings: ["Saunf tea", "Buttermilk with jeera", "Roasted makhana", "Handful of soaked raisins"],
    dinners: [
      "Moong dal khichdi with 1 tsp ghee — early, by 7:30 pm",
      "Vegetable soup + 1 roti",
      "Soft dal with 1 roti and steamed vegetables",
      "Dalia with vegetables",
    ],
    bedtime: ["Warm water with saunf", "Isabgol — 1 tsp, if constipated"],
    practices: ["Vajrasana for 5-10 min after meals", "Walk 15 min after dinner", "Do not lie down for 2 hours after eating"],
    guidelines: [
      "Eat slowly and chew properly. This alone resolves a meaningful share of cases.",
      "Smaller, more frequent meals rather than three large ones.",
      "Finish dinner by 7:30 pm and do not lie down for 2 hours afterwards.",
      "Cooked vegetables over large raw salads — raw fibre is hard work for some people.",
      "Log food and symptoms daily for 2-3 weeks. The pattern is invisible without it.",
      "See a doctor first for blood in stool, unexplained weight loss, persistent vomiting or difficulty swallowing.",
    ],
    notes: ["We remove nothing permanently without a reintroduction plan written down first."],
  },
  {
    key: "constipation",
    label: "Constipation & Irregularity",
    category: "Digestive",
    conditions: ["Digestive issues"],
    dietPreference: "Vegetarian",
    focus: "Fibre, fluid and movement — the unglamorous fundamentals, done properly.",
    wakeup: ["Warm water — 2 glasses on an empty stomach", "5 soaked raisins or 2 soaked anjeer", "Walk 10 min"],
    breakfasts: [
      "Vegetable dalia with 1 tsp ghee",
      "Oats with soaked chia and fruit",
      "Poha with vegetables",
      "2 multigrain roti with sabzi",
    ],
    midMorning: ["Papaya — 1 katori", "Guava with seeds", "Orange", "Buttermilk"],
    lunches: [
      "2 multigrain roti + dal + palak sabzi + curd + salad",
      "Brown rice + rajma + large salad",
      "2 jowar roti + chana dal + bhindi + curd",
      "Vegetable khichdi with ghee and curd",
    ],
    evenings: ["Roasted chana", "Soaked prunes or anjeer", "Buttermilk", "Fruit with skin"],
    dinners: [
      "1 roti + dal + sautéed greens",
      "Vegetable soup + 1 roti",
      "Khichdi with 1 tsp ghee",
      "Dal with steamed vegetables and 1 roti",
    ],
    bedtime: ["Warm milk with 1 tsp ghee", "Isabgol — 1 tsp in warm water"],
    practices: ["Walk 30 min daily", "Pawanmuktasana and Malasana", "Do not suppress the urge — go when you feel it"],
    guidelines: [
      "3 litres of water a day. Fibre without fluid makes constipation worse, not better.",
      "1 tsp ghee at night is genuinely effective and widely underused.",
      "Fruit with the skin on where edible — guava, apple, pear.",
      "Same time every morning, unhurried. Routine matters as much as diet.",
      "Increase fibre gradually over 2 weeks, or you will bloat.",
    ],
  },
  {
    key: "ibs-starter",
    label: "IBS-type Symptoms — Structured Start",
    category: "Digestive",
    conditions: ["Digestive issues"],
    dietPreference: "Vegetarian",
    focus: "A time-limited, low-trigger baseline with a written reintroduction plan — never open-ended elimination.",
    wakeup: ["Warm water with saunf", "Chew ½ inch ginger", "5 soaked and peeled almonds"],
    breakfasts: [
      "Rice poha with carrot and 1 tsp oil",
      "Moong dal cheela — plain, with pudhina chutney",
      "Oats cooked in lactose-free milk or water",
      "Rice idli — 2, with mild coconut chutney",
    ],
    midMorning: ["Papaya", "Banana — ripe but not overripe", "Orange", "Rice cakes with peanut butter"],
    lunches: [
      "Rice + moong dal + carrot and beans sabzi + curd if tolerated",
      "Rice + toor dal + lauki sabzi",
      "Khichdi with 1 tsp ghee and steamed vegetables",
      "Rice + palak dal + zucchini sabzi",
    ],
    evenings: ["Saunf tea", "Rice cakes", "Roasted makhana", "Papaya"],
    dinners: [
      "Soft khichdi with ghee — early",
      "Rice with moong dal and steamed vegetables",
      "Clear vegetable soup with rice",
      "Rice idli with mild chutney",
    ],
    bedtime: ["Warm water with saunf"],
    guidelines: [
      "This is a 3-4 week baseline, not a permanent diet. The goal is the widest range of foods you can eat comfortably.",
      "Log every meal and every symptom, with times. The correlation is the whole point.",
      "Reintroduce one food group at a time, over 3 days each, and record what happens.",
      "Wheat, onion, garlic, rajma, chole and large raw salads are held back at the start and tested later.",
      "Commercial food intolerance blood tests are not reliable. This is.",
      "We provide nutrition support alongside your doctor's care. We do not diagnose IBS.",
    ],
  },
  {
    key: "pregnancy-t2",
    label: "Pregnancy — Second Trimester",
    category: "Life stage",
    conditions: ["Currently pregnant"],
    dietPreference: "Vegetarian",
    focus: "Adequate energy, protein, iron, calcium and folate — always led by your obstetrician.",
    wakeup: ["Warm water", "5 soaked almonds + 2 walnuts", "1 date"],
    breakfasts: [
      "Vegetable dalia with milk",
      "2 besan chilla with curd",
      "Paneer stuffed roti with 1 tsp ghee",
      "Oats with milk, dates and nuts",
    ],
    midMorning: ["Fruit + handful of nuts", "Milk — 1 glass", "Coconut water", "Curd with fruit"],
    lunches: [
      "2 roti + dal + palak sabzi + curd + salad",
      "Rice + rajma + curd + salad",
      "2 roti + paneer sabzi + dal + salad",
      "Khichdi with ghee, curd and vegetables",
    ],
    evenings: ["Sprouts chaat", "Milk with dates", "Fruit and nuts", "Buttermilk"],
    dinners: [
      "2 roti + dal + sautéed greens + curd",
      "Vegetable khichdi with ghee",
      "Paneer sabzi with roti and salad",
      "Dal with rice and vegetables",
    ],
    bedtime: ["Warm milk with turmeric"],
    supplements: ["Only what your obstetrician has prescribed — folic acid, iron, calcium as directed"],
    guidelines: [
      "Your obstetrician leads. If their advice differs from anything here, follow theirs and tell us.",
      "This is not a weight-loss plan and must not be used as one.",
      "Iron with vitamin C: palak with lemon, jaggery with amla. Keep tea and coffee away from iron-rich meals.",
      "Food safety: no unpasteurised dairy, raw sprouts, undercooked egg or unwashed produce.",
      "Small frequent meals if nausea or heartburn is a problem.",
      "Report any bleeding, severe swelling or reduced foetal movement to your doctor immediately.",
    ],
    notes: ["Weight gain range is set by your obstetrician, not by us."],
  },
  {
    key: "postnatal",
    label: "Post-natal & Lactation",
    category: "Life stage",
    conditions: ["Recently gave birth"],
    dietPreference: "Vegetarian",
    focus: "Recovery, milk supply and eating realistically with a newborn in the house.",
    wakeup: ["Warm water with ajwain", "5 soaked almonds", "Gond or methi ladoo — 1 small"],
    breakfasts: [
      "Vegetable dalia with milk and ghee",
      "Paneer paratha with curd",
      "Oats with milk, dates and nuts",
      "2 besan chilla with curd",
    ],
    midMorning: ["Milk with haldi", "Fruit and nuts", "Coconut water", "Dry fruit ladoo"],
    lunches: [
      "2-3 roti with ghee + dal + palak sabzi + curd",
      "Rice + rajma + curd + ghee",
      "Khichdi with ghee, curd and vegetables",
      "2 roti + paneer sabzi + dal + salad",
    ],
    evenings: ["Milk with dates", "Sprouts chaat", "Sesame ladoo", "Fruit with nuts"],
    dinners: [
      "2 roti + dal + sautéed greens + curd",
      "Vegetable khichdi with ghee",
      "Dal, rice and vegetables",
      "Paneer sabzi with roti",
    ],
    bedtime: ["Warm milk with turmeric and 1 tsp ghee"],
    guidelines: [
      "Do not restrict calories while breastfeeding. Milk supply comes first.",
      "3 to 3.5 litres of fluid daily — keep a bottle wherever you feed.",
      "Keep one-handed snacks within reach: nuts, ladoo, fruit, milk.",
      "Methi, saunf, ajwain and gond are traditional galactagogues and are safe in normal amounts.",
      "Continue iron and calcium as your doctor has advised.",
      "Weight comes off gradually over months. It is not the priority right now.",
    ],
  },
  {
    key: "muscle-gain-veg",
    label: "Muscle Gain — Vegetarian",
    category: "Performance",
    conditions: [],
    dietPreference: "Vegetarian",
    focus: "Hitting protein on an Indian vegetarian diet — the problem most plans handle badly.",
    wakeup: ["Warm water", "10 soaked almonds + 4 walnuts", "1 scoop protein with milk (optional)"],
    breakfasts: [
      "4 egg-free: paneer bhurji 100 gm with 2 multigrain roti",
      "Moong dal cheela x3 with curd",
      "Oats with milk, peanut butter and banana",
      "Besan chilla x2 stuffed with paneer",
    ],
    midMorning: ["Sprouts chaat — 1 large katori", "Greek yoghurt with fruit", "Peanut butter toast", "Milkshake with dates"],
    lunches: [
      "3 roti + dal + paneer sabzi + curd + salad",
      "1.5 katori rice + rajma + curd + salad",
      "3 roti + soya chunk curry + curd",
      "Quinoa + chana + paneer 100 gm + vegetables",
    ],
    evenings: ["1 scoop protein + banana", "Sprouts with peanuts", "Greek yoghurt", "Paneer tikka — 100 gm"],
    dinners: [
      "2 roti + paneer sabzi 150 gm + dal + salad",
      "Soya chunk pulao with raita",
      "Tofu stir-fry with 2 roti",
      "Dal + rice + paneer + sautéed greens",
    ],
    bedtime: ["Milk with 1 tsp ghee", "Casein or milk protein if training hard"],
    supplements: ["Whey or plant protein — 1-2 scoops as needed", "Creatine 3-5 gm, if you choose to use it"],
    practices: ["Progressive strength training 4-5x/week", "Sleep 7-8 hours — growth happens here"],
    guidelines: [
      "Protein target is roughly 1.6-2 gm per kg bodyweight. Spread it across 4-5 feeds, not one shake.",
      "Dal alone will not get you there. Paneer, curd, soya, tofu and sprouts do the heavy lifting.",
      "Combine cereals and pulses across the day for a complete amino acid profile.",
      "Do not cut carbohydrate while training hard — you will end up weak and flat.",
      "Gain 0.25-0.5 kg a week. Faster is mostly fat.",
    ],
  },
  {
    key: "night-shift",
    label: "Night Shift Worker",
    category: "Lifestyle",
    conditions: [],
    dietPreference: "Vegetarian",
    focus: "Anchoring meals to the shift rather than the clock, and protecting sleep on the other side of it.",
    wakeup: ["On waking (afternoon): warm water with lemon", "5 soaked almonds", "Fruit"],
    breakfasts: [
      "First meal after waking: vegetable oats with curd",
      "2 besan chilla with chutney",
      "Poha with peanuts and vegetables",
      "2 roti with paneer bhurji",
    ],
    midMorning: ["Fruit and nuts", "Buttermilk", "Roasted chana", "Green tea"],
    lunches: [
      "Pre-shift main meal: 2 roti + dal + sabzi + curd + salad",
      "Rice + rajma + salad + curd",
      "Khichdi with curd and vegetables",
      "2 roti + paneer sabzi + salad",
    ],
    evenings: ["Mid-shift: sprouts chaat", "Roasted makhana + green tea", "Fruit with nuts", "Buttermilk"],
    dinners: [
      "Light mid-shift meal: vegetable soup + 1 roti",
      "Moong dal khichdi — small portion",
      "Dal with 1 roti and salad",
      "Curd rice — 1 small katori",
    ],
    bedtime: ["Post-shift, before sleeping: warm milk — keep it light"],
    guidelines: [
      "Eat your largest meal before the shift, not during it.",
      "Keep the 2 am stretch light — heavy food at that hour worsens both alertness and digestion.",
      "No caffeine in the second half of the shift, or sleep afterwards will not happen.",
      "Blackout curtains and a fixed sleep window matter as much as the food here.",
      "Night shift raises metabolic risk. Annual blood sugar and lipid checks are worth it.",
    ],
  },
  {
    key: "traveller",
    label: "Frequent Traveller",
    category: "Lifestyle",
    conditions: [],
    focus: "Built for hotels, airports and restaurant menus — because a plan that only works at home fails by week two.",
    wakeup: ["Warm water with lemon", "Almonds from your travel pouch", "Black coffee if needed"],
    breakfasts: [
      "Hotel buffet: 2 idli + sambar, or 2 eggs + 1 toast + fruit",
      "Poha or upma — 1 plate, skip the fried sides",
      "Curd + fruit + a handful of nuts",
      "Oats with milk if available",
    ],
    midMorning: ["Travel pouch: almonds, walnuts, roasted chana", "Fruit", "Coconut water", "Buttermilk"],
    lunches: [
      "Restaurant: 2 roti + dal + a dry sabzi + salad + curd. Ask for less oil.",
      "Rice + dal + grilled protein + salad",
      "Thali — eat the dal, sabzi, curd and salad, leave the fried items",
      "Grilled sandwich with vegetables + soup",
    ],
    evenings: ["Green tea + nuts from the pouch", "Fruit", "Buttermilk", "Roasted chana"],
    dinners: [
      "Soup + grilled protein or paneer + salad",
      "1-2 roti + dal + dry sabzi",
      "Khichdi if available — ask, most kitchens will make it",
      "Curd rice with salad",
    ],
    bedtime: ["Warm water"],
    guidelines: [
      "Carry a pouch: almonds, walnuts, roasted chana, a few dates. It removes most bad airport decisions.",
      "Order dry over gravy, tandoori over fried, and ask for less oil. Kitchens will do it.",
      "Two litres of water on any flight over three hours.",
      "Alcohol and airline food together are what actually wreck the week.",
      "One indulgent meal a trip is planned for, not a failure.",
    ],
  },
  {
    key: "student-hostel",
    label: "Student / Hostel Mess",
    category: "Lifestyle",
    conditions: [],
    dietPreference: "Vegetarian",
    focus: "Works off a mess menu with almost no cooking and a small budget.",
    wakeup: ["Warm water", "5 almonds soaked overnight in a mug"],
    breakfasts: [
      "Mess: 2 idli/dosa + sambar, or poha, plus 1 boiled egg or curd",
      "Bread with peanut butter + banana + milk",
      "Upma or poha from the mess + curd",
      "Oats made with hot water in a mug + banana",
    ],
    midMorning: ["Banana", "Roasted chana packet", "Peanuts", "Buttermilk"],
    lunches: [
      "Mess thali: take the dal and sabzi generously, rice moderately, add curd and salad",
      "Rajma or chole day: take a full katori, less rice",
      "2 roti + dal + sabzi + curd",
      "Curd rice with a boiled egg or paneer",
    ],
    evenings: ["Roasted chana or peanuts", "Banana with peanut butter", "Sprouts if available", "Tea without sugar"],
    dinners: [
      "Mess dinner: dal + 2 roti + sabzi + salad",
      "Khichdi night: take it with curd",
      "Rice + dal + curd",
      "Roti + paneer sabzi when it appears",
    ],
    bedtime: ["Milk if available"],
    guidelines: [
      "At the mess, fill the plate in this order: salad, then dal or sabzi, then rice or roti.",
      "Keep a personal stock of peanuts, roasted chana, almonds, peanut butter and oats. That is the whole budget.",
      "Two eggs or a katori of curd a day covers most of the protein gap.",
      "Maggi and fried snacks twice a week at most, not daily.",
      "Sleep and screen time affect this more than any food choice at your age.",
    ],
  },
  {
    key: "festival-season",
    label: "Festival & Wedding Season",
    category: "Lifestyle",
    conditions: [],
    dietPreference: "Vegetarian",
    focus: "Getting through the season without abandoning the plan — damage control, planned in advance.",
    wakeup: ["Warm water with lemon", "5 soaked almonds", "Methre wala paani"],
    breakfasts: [
      "Light and protein-led: 2 besan chilla with curd",
      "Vegetable oats — 1 katori",
      "Moong dal cheela with chutney",
      "Curd with fruit and seeds",
    ],
    midMorning: ["Fruit", "Buttermilk", "Roasted chana", "Green tea"],
    lunches: [
      "On a function day: eat a normal light lunch, never skip it",
      "2 roti + dal + sabzi + curd + salad",
      "Khichdi with curd",
      "Salad-heavy plate with dal and 1 roti",
    ],
    evenings: ["Before a function: curd or buttermilk + a handful of nuts", "Sprouts chaat", "Green tea", "Fruit"],
    dinners: [
      "At the function: salad and starters first, then one plate. Sit down to eat it.",
      "Non-function night: soup + 1 roti + dal",
      "Khichdi to reset after a heavy day",
      "Vegetable soup with paneer",
    ],
    bedtime: ["Warm water with saunf", "Triphala if the day was heavy"],
    guidelines: [
      "Never go to a function hungry. Curd or nuts beforehand decides how the evening goes.",
      "Salad and starters first, then one plate. Sitting down halves what you eat.",
      "Sweets: two pieces, chosen deliberately, eaten slowly. Not grazing all evening.",
      "Alcohol adds up faster than the food does.",
      "The next morning is a normal breakfast, not a fast. Skipping is what starts the cycle.",
      "A 20-minute walk the morning after every function.",
    ],
    notes: ["The season is 6-8 weeks. The aim is to arrive at the other side unchanged, not to lose weight through it."],
  },
];
