import type { Profile } from "./types.ts";

/** Weight, metabolic and hormonal profiles. */
export const PROFILES_A: Profile[] = [
  {
    key: "weight-loss-veg",
    label: "Weight Loss",
    category: "Weight",
    conditions: ["Weight management"],
    dietPreference: "Vegetarian",
    focus: "Steady fat loss on home food — portion, timing and protein at every meal, without removing rice or roti.",
    wakeup: ["Warm water with lemon", "5 soaked and peeled almonds + 2 walnuts", "Methre wala paani — 1 glass"],
    breakfasts: [
      "Vegetable poha with peanuts — 1 medium bowl, with 1 katori curd",
      "2 besan chilla with dhaniya pudhina chutney",
      "Moong dal cheela with grated paneer — 2 pieces",
      "Vegetable oats with 1 tsp flaxseed powder — 1 katori",
      "2 multigrain roti with sabzi and 1 katori curd",
    ],
    midMorning: ["Guava or apple + buttermilk", "Roasted chana — 1 small katori", "Papaya — 1 katori", "Coconut water with soaked chia"],
    lunches: [
      "Salad first, then 2 roti + 1 katori dal + green sabzi + 1 katori curd",
      "1 katori brown rice + rajma + large salad + curd",
      "2 jowar roti + chana dal + lauki sabzi + kachumber",
      "Vegetable khichdi with 1 tsp ghee + curd + salad",
      "2 roti + paneer bhurji (low oil) + salad",
    ],
    evenings: ["Roasted chana + green tea", "Sprouts chaat — 1 katori", "Buttermilk + 5 almonds", "Roasted makhana — 1 katori"],
    dinners: [
      "1 roti + dal + sabzi + salad — finish by 8:30 pm",
      "Moong dal khichdi with curd — 1 katori",
      "Vegetable soup + 1 multigrain roti with paneer sabzi",
      "1 katori quinoa + mixed vegetable sabzi + curd",
    ],
    bedtime: ["Warm turmeric milk — 1 cup, if hungry"],
    practices: ["Walk 20 mins after lunch and dinner", "Anulom vilom — 10 min"],
    guidelines: [
      "Salad before the carbohydrate portion at every main meal.",
      "Protein at all three meals — dal, curd, paneer or sprouts.",
      "Oil limit: 3 tsp per person per day.",
      "Finish dinner by 8:30 pm; nothing but water afterwards.",
      "Weigh once a week, same day, same time, after using the toilet.",
      "No sugary drinks, packaged juice or bakery items.",
    ],
    notes: ["Rice and roti stay in the plan — the portion is what changes.", "A missed day is not a failed week. Log it and carry on."],
  },
  {
    key: "weight-loss-nonveg",
    label: "Weight Loss",
    category: "Weight",
    conditions: ["Weight management"],
    dietPreference: "Non-vegetarian",
    focus: "Fat loss with lean protein at lunch and dinner — higher satiety, easier adherence.",
    wakeup: ["Warm water with lemon", "5 soaked almonds", "Black coffee, no sugar (optional)"],
    breakfasts: [
      "2 egg white omelette + 1 multigrain toast",
      "3 boiled eggs (2 whole, 1 white) with sautéed vegetables",
      "Vegetable oats with 1 boiled egg",
      "2 besan chilla with curd",
      "Egg bhurji with 1 roti and salad",
    ],
    midMorning: ["Guava or apple", "Buttermilk", "Roasted chana", "10 almonds and 2 walnuts"],
    lunches: [
      "Salad + 2 roti + 100 gm grilled chicken + green sabzi",
      "1 katori brown rice + fish curry (1 tsp oil) + salad",
      "2 roti + chicken keema with peas + kachumber",
      "Salad + 1 katori rice + dal + 100 gm chicken tikka",
    ],
    evenings: ["Green tea + roasted chana", "Buttermilk", "Sprouts chaat", "Boiled egg white x2"],
    dinners: [
      "Grilled fish or chicken 120 gm + sautéed vegetables + 1 roti",
      "Chicken clear soup + 4 egg whites in any form + salad",
      "1 roti + egg curry (low oil) + salad",
      "Chopped vegetable soup with shredded chicken — 1 large bowl",
    ],
    bedtime: ["Warm water with a pinch of cinnamon"],
    practices: ["Walk 20 mins after dinner", "Strength training 3x/week"],
    guidelines: [
      "Grill, bake or pressure-cook — no deep frying.",
      "Keep red meat to once a week at most.",
      "Salad before the main portion at lunch and dinner.",
      "Oil limit: 3 tsp per person per day.",
      "Finish dinner by 8:30 pm.",
    ],
  },
  {
    key: "weight-loss-vegan",
    label: "Weight Loss",
    category: "Weight",
    conditions: ["Weight management"],
    dietPreference: "Vegan",
    focus: "Plant-only fat loss with deliberate protein sourcing — the gap most vegan plans miss.",
    wakeup: ["Warm water with lemon", "5 soaked almonds + 2 walnuts", "1 tsp soaked chia"],
    breakfasts: [
      "Moong dal cheela with coconut chutney — 2 pieces",
      "Vegetable poha with peanuts and 1 tsp flaxseed",
      "Oats cooked in almond milk with seeds",
      "Besan chilla with tomato chutney",
      "Tofu bhurji with 1 multigrain roti",
    ],
    midMorning: ["Coconut water with chia", "Guava or pear", "Roasted chana", "Handful of peanuts"],
    lunches: [
      "Salad + 2 roti + rajma + sautéed greens",
      "1 katori brown rice + chana + salad + 1 tsp olive oil",
      "2 jowar roti + soya chunk sabzi + kachumber",
      "Quinoa + mixed vegetables + tofu 100 gm",
    ],
    evenings: ["Sprouts chaat", "Roasted makhana", "Green tea + almonds", "Peanut chaat — 1 small katori"],
    dinners: [
      "Moong dal khichdi with vegetables — 1 katori",
      "Vegetable soup + 1 roti with tofu sabzi",
      "1 katori dal + sautéed greens + 1 roti",
      "Chana salad bowl with olive oil and lemon",
    ],
    bedtime: ["Warm almond milk with turmeric"],
    supplements: ["B12 — as advised by your doctor", "Omega 3 (algal) — 1 cap"],
    guidelines: [
      "Protein at every meal — dal, chana, rajma, soya, tofu or peanuts.",
      "Combine grains and pulses across the day for a complete amino profile.",
      "B12 needs supplementing on a vegan diet — discuss the dose with your doctor.",
      "Oil limit: 3 tsp per person per day.",
    ],
  },
  {
    key: "weight-loss-jain",
    label: "Weight Loss",
    category: "Weight",
    conditions: ["Weight management"],
    dietPreference: "Jain",
    focus: "Fat loss without root vegetables, onion or garlic — protein from dals, curd and paneer.",
    wakeup: ["Warm water with lemon", "5 soaked almonds"],
    breakfasts: [
      "Moong dal cheela with dhaniya chutney — 2 pieces",
      "Vegetable poha (no onion) with peanuts",
      "Besan chilla with curd",
      "Oats with milk and seeds",
      "2 roti with lauki sabzi and curd",
    ],
    midMorning: ["Guava or apple", "Buttermilk with jeera", "Roasted chana", "Papaya — 1 katori"],
    lunches: [
      "2 roti + moong dal + lauki sabzi + curd",
      "1 katori rice + chana dal + tinda sabzi + salad",
      "2 jowar roti + paneer sabzi (no onion) + cucumber salad",
      "Vegetable khichdi with curd and 1 tsp ghee",
    ],
    evenings: ["Roasted makhana", "Buttermilk", "Green tea + almonds", "Sprouted moong — 1 katori"],
    dinners: [
      "1 roti + dal + gheeya sabzi",
      "Moong dal khichdi — 1 katori with curd",
      "Vegetable soup + 1 roti with paneer",
      "1 katori dal + sautéed bottle gourd",
    ],
    bedtime: ["Warm turmeric milk"],
    guidelines: [
      "No onion, garlic, potato, carrot, beetroot, radish or other root vegetables.",
      "Protein comes from dals, curd, paneer and sprouted moong — include one at every meal.",
      "Eat before sunset where you observe it; the plan is built to work either way.",
      "Oil limit: 3 tsp per person per day.",
    ],
  },
  {
    key: "weight-gain",
    label: "Healthy Weight Gain",
    category: "Weight",
    conditions: ["Underweight"],
    dietPreference: "Vegetarian",
    focus: "Calorie density over volume — more frequent, more digestible, at times appetite allows.",
    wakeup: ["Warm milk with soaked dates — 1 glass", "10 soaked almonds + 4 walnuts"],
    breakfasts: [
      "2 stuffed paratha with 1 tsp ghee and curd",
      "Banana peanut butter shake + 2 besan chilla",
      "Poha with peanuts + 1 glass full-fat milk",
      "Oats cooked in full milk with dates and nuts",
      "3 idli with sambar and coconut chutney",
    ],
    midMorning: ["Banana milkshake", "Mango or chikoo shake", "Dry fruit ladoo — 1 piece", "Sprouts chaat with peanuts"],
    lunches: [
      "3 roti with ghee + dal + paneer sabzi + curd + salad",
      "1.5 katori rice + rajma + curd + 1 tsp ghee",
      "3 roti + chole + rice + curd",
      "Vegetable pulao with paneer + raita",
    ],
    evenings: ["Peanut chikki + milk", "Banana with peanut butter", "Dry fruit and seed mix — 1 katori", "Lassi — 1 glass"],
    dinners: [
      "2-3 roti + paneer sabzi + dal + curd",
      "Vegetable khichdi with ghee + curd",
      "2 roti + soya chunk curry + rice",
      "Paratha with curd and pickle",
    ],
    bedtime: ["Full-fat milk with 1 tsp ghee and turmeric"],
    guidelines: [
      "Never drink water immediately before a meal — it reduces how much you can eat.",
      "Eat every 2.5 to 3 hours, even when not hungry.",
      "Resistance training 3 to 4 times a week, or the gain will be fat rather than muscle.",
      "Target roughly 0.25 to 0.5 kg a week. Faster than that is mostly fat.",
      "If the weight loss was recent or unexplained, see a doctor before continuing.",
    ],
  },
  {
    key: "diabetes-veg",
    label: "Type 2 Diabetes",
    category: "Metabolic",
    conditions: ["Diabetes"],
    dietPreference: "Vegetarian",
    focus: "Carbohydrate distribution, pairing and meal spacing — not elimination.",
    wakeup: ["Methre wala paani — 1 glass, overnight soaked", "5 soaked almonds + 2 walnuts", "Chew ½ inch raw ginger"],
    breakfasts: [
      "Vegetable oats with 1 tsp flaxseed — 1 katori, with curd",
      "2 moong dal cheela with dhaniya pudhina chutney",
      "2 multigrain roti with sabzi and 1 katori curd",
      "Besan chilla with paneer stuffing — 2 pieces",
      "Vegetable dalia — 1 katori with curd",
    ],
    midMorning: ["Guava — 1 whole", "Buttermilk with jeera", "Roasted chana — 1 small katori", "5 almonds + green tea"],
    lunches: [
      "Salad first, then 2 multigrain roti + 1 katori dal + green sabzi + curd",
      "1 katori brown rice + rajma + large salad + curd",
      "2 jowar roti + chana dal + methi sabzi + kachumber",
      "Vegetable khichdi (kodo or moong) with curd and salad",
    ],
    evenings: ["Roasted chana + green tea", "Sprouts chaat — 1 katori", "Buttermilk", "Roasted makhana"],
    dinners: [
      "1-2 roti + paneer sabzi + salad — by 8:30 pm",
      "Moong dal khichdi with curd and salad",
      "Vegetable soup + 1 multigrain roti with dal",
      "1 katori dal + sautéed greens + 1 roti",
    ],
    bedtime: ["Warm water with a pinch of cinnamon"],
    practices: ["Walk 10 mins after lunch and dinner — non-negotiable", "Anulom vilom — 10 min"],
    guidelines: [
      "Never eat a carbohydrate alone — always pair with protein, fat or fibre.",
      "Salad before the roti or rice portion at every main meal.",
      "Do not leave gaps longer than 4 hours between meals.",
      "A 10-minute walk after lunch and dinner is the single highest-return habit here.",
      "Log your readings alongside meals so the pattern becomes visible.",
      "Continue all medication exactly as your doctor prescribed. Nothing here replaces it.",
    ],
    notes: ["Rice is allowed — measured, paired, and not at night in large quantity.", "Fruit is allowed whole. Fruit juice is not."],
  },
  {
    key: "diabetes-nonveg",
    label: "Type 2 Diabetes",
    category: "Metabolic",
    conditions: ["Diabetes"],
    dietPreference: "Non-vegetarian",
    focus: "Lean protein anchoring each meal to blunt the glucose response.",
    wakeup: ["Methre wala paani — 1 glass", "5 soaked almonds", "Chew ½ inch raw ginger"],
    breakfasts: [
      "2 egg white omelette with vegetables + 1 multigrain toast",
      "3 boiled eggs with sautéed spinach",
      "Vegetable oats with 1 boiled egg",
      "Egg bhurji with 1 multigrain roti",
    ],
    midMorning: ["Guava", "Buttermilk", "Roasted chana", "5 almonds + green tea"],
    lunches: [
      "Salad + 2 multigrain roti + 100 gm grilled chicken + green sabzi",
      "1 katori brown rice + fish curry + large salad",
      "2 roti + chicken keema with peas + kachumber",
      "Salad + dal + 1 katori rice + grilled fish 100 gm",
    ],
    evenings: ["Green tea + roasted chana", "Boiled egg whites x2", "Buttermilk", "Sprouts chaat"],
    dinners: [
      "Grilled fish 120 gm + sautéed vegetables + 1 roti — by 8:30 pm",
      "Chicken clear soup + 4 egg whites + salad",
      "1 roti + egg curry + salad",
      "Chopped vegetable soup with shredded chicken",
    ],
    bedtime: ["Warm water with cinnamon"],
    practices: ["Walk 10 mins after lunch and dinner", "Strength training 3x/week"],
    guidelines: [
      "Grill, bake or pressure-cook. No deep frying.",
      "Salad before the carbohydrate portion at every main meal.",
      "No gaps longer than 4 hours between meals.",
      "Continue all medication as prescribed by your doctor.",
    ],
  },
  {
    key: "prediabetes",
    label: "Pre-diabetes & Insulin Resistance",
    category: "Metabolic",
    conditions: ["Pre-diabetes"],
    dietPreference: "Vegetarian",
    focus: "The window where nutrition has the most leverage — act before it progresses.",
    wakeup: ["Methre wala paani — 1 glass", "5 soaked almonds + 2 walnuts"],
    breakfasts: [
      "Vegetable oats with flaxseed and curd",
      "2 moong dal cheela with chutney",
      "Besan chilla with paneer — 2 pieces",
      "2 multigrain roti with sabzi and curd",
    ],
    midMorning: ["Guava", "Buttermilk", "Roasted chana", "Handful of walnuts"],
    lunches: [
      "Salad + 2 multigrain roti + dal + green sabzi + curd",
      "Brown rice + rajma + salad + curd",
      "2 jowar roti + chana dal + methi sabzi",
      "Kodo khichdi with curd and salad",
    ],
    evenings: ["Roasted chana + green tea", "Sprouts chaat", "Buttermilk", "Makhana"],
    dinners: [
      "1-2 roti + paneer sabzi + salad",
      "Moong dal khichdi with curd",
      "Vegetable soup + 1 roti with dal",
      "Dal + sautéed greens + 1 roti",
    ],
    bedtime: ["Warm water with cinnamon"],
    practices: ["Walk 30-40 min daily", "Strength training 3x/week — muscle improves glucose handling"],
    guidelines: [
      "This is the stage where changes make the most difference. Consistency now is worth more than intensity later.",
      "Build muscle — it is the body's largest glucose sink.",
      "Sleep before 11 pm. Short sleep worsens insulin resistance directly.",
      "Retest HbA1c after 3 months, as your doctor advises.",
    ],
  },
  {
    key: "fatty-liver",
    label: "Fatty Liver",
    category: "Metabolic",
    conditions: ["Fatty liver"],
    dietPreference: "Vegetarian",
    focus: "Reduce liver fat through refined-carb and fructose control, with steady weight reduction.",
    wakeup: ["Warm water with lemon", "Methre wala paani", "5 soaked almonds + 2 walnuts"],
    breakfasts: [
      "Vegetable oats with flaxseed — 1 katori",
      "2 moong dal cheela with chutney",
      "Besan chilla with curd",
      "2 multigrain roti with sabzi",
    ],
    midMorning: ["Guava or apple", "Buttermilk", "Roasted chana", "Coconut water"],
    lunches: [
      "Salad + 2 multigrain roti + dal + green sabzi + curd",
      "Brown rice + rajma + large salad",
      "2 jowar roti + chana dal + lauki sabzi",
      "Kodo vegetable khichdi with curd",
    ],
    evenings: ["Green tea + roasted chana", "Sprouts chaat", "Buttermilk", "Makhana"],
    dinners: [
      "Tofu or paneer sabzi with 1 roti and salad",
      "Moong dal khichdi with curd",
      "Vegetable soup + 1 roti with dal",
      "Dal + sautéed greens + 1 roti",
    ],
    bedtime: ["Warm water"],
    supplements: ["Omega 3 — 1 cap", "Curcumin — as advised"],
    practices: ["Walk 30-40 min twice a day", "Strength training 4x/week"],
    guidelines: [
      "No alcohol. This matters more here than any food change.",
      "No packaged juice, cold drinks or sweetened beverages — fructose goes straight to the liver.",
      "Cut maida entirely: bread, biscuits, bakery, instant noodles.",
      "Oil limit: 3 tsp per person per day.",
      "Even 5-7% weight reduction meaningfully improves liver fat.",
    ],
  },
  {
    key: "cholesterol",
    label: "High Cholesterol",
    category: "Metabolic",
    conditions: ["High cholesterol"],
    dietPreference: "Vegetarian",
    focus: "Fat quality over fat quantity, plus soluble fibre — the two levers with the best evidence.",
    wakeup: ["Warm water with lemon", "5 soaked almonds + 2 walnuts", "1 tsp soaked flaxseed"],
    breakfasts: [
      "Oats with 1 tsp flaxseed powder — 1 katori",
      "Vegetable dalia with curd",
      "2 moong dal cheela with chutney",
      "Besan chilla with vegetables",
    ],
    midMorning: ["Apple with skin", "Guava", "Handful of walnuts", "Buttermilk"],
    lunches: [
      "Salad + 2 multigrain roti + rajma + green sabzi",
      "Brown rice + chana + large salad",
      "2 jowar roti + dal + methi sabzi + curd",
      "Barley khichdi with vegetables",
    ],
    evenings: ["Green tea + roasted chana", "Sprouts chaat", "5 walnuts", "Makhana"],
    dinners: [
      "1 roti + dal + sautéed greens + salad",
      "Vegetable soup + 1 roti with paneer",
      "Moong dal khichdi with curd",
      "Oats khichdi with vegetables",
    ],
    bedtime: ["Warm water"],
    guidelines: [
      "Replace part of your cooking fat with mustard, rice bran or olive oil. Do not reuse frying oil, ever.",
      "Soluble fibre daily: oats, barley, rajma, chana, apple or 1 tsp flaxseed.",
      "Cut vanaspati, bakery items and packaged namkeen entirely.",
      "Triglycerides respond to sugar and refined carbohydrate more than to dietary fat.",
      "Walk 30-40 min daily — it raises HDL.",
      "Recheck your lipid profile when your doctor advises, usually around 3 months.",
    ],
  },
  {
    key: "hypertension",
    label: "High Blood Pressure",
    category: "Metabolic",
    conditions: ["High blood pressure"],
    dietPreference: "Vegetarian",
    focus: "Sodium reduction with potassium, magnesium and calcium adequacy — a DASH-style pattern in Indian food.",
    wakeup: ["Warm water with lemon", "5 soaked almonds + 2 walnuts", "1 banana (if potassium is not restricted)"],
    breakfasts: [
      "Vegetable oats — 1 katori, no added salt at table",
      "2 besan chilla with dhaniya chutney",
      "Poha with peanuts and vegetables",
      "2 multigrain roti with sabzi and curd",
    ],
    midMorning: ["Banana or orange", "Buttermilk without salt", "Coconut water", "Handful of unsalted nuts"],
    lunches: [
      "Salad + 2 roti + dal + green sabzi + curd",
      "Brown rice + rajma + salad",
      "2 jowar roti + chana dal + palak sabzi",
      "Vegetable khichdi with curd",
    ],
    evenings: ["Green tea + unsalted makhana", "Fruit", "Buttermilk", "Roasted chana, unsalted"],
    dinners: [
      "1 roti + dal + sautéed greens",
      "Vegetable soup, low salt + 1 roti",
      "Moong dal khichdi with curd",
      "Paneer sabzi with 1 roti and salad",
    ],
    bedtime: ["Warm milk"],
    practices: ["Walk 30-40 min daily", "Anulom vilom and bhramari — 10 min, morning and night"],
    guidelines: [
      "Salt limit: under 5 gm a day — roughly 1 level teaspoon including what is used in cooking.",
      "No papad, pickle, packaged namkeen, sauces or processed food.",
      "Do not add salt at the table.",
      "Potassium-rich foods daily: banana, coconut water, palak, beans — unless your doctor has restricted potassium.",
      "Log your BP readings so the pattern is visible at review.",
      "Continue all medication as prescribed.",
    ],
  },
];
